[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
port.workspace = true
domain.workspace = true
driver.workspace = true

async-trait.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
