[package]
name = "usecase"
version = "0.1.0"
edition = "2024"

[dependencies]
domain.workspace = true
port.workspace = true

anyhow.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio.workspace = true
