[package]
name = "handler"
version = "0.1.0"
edition = "2024"

[dependencies]
usecase.workspace = true

axum.workspace = true
serde.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
